# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exercise_sensors.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import structures_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='exercise_sensors.proto',
  package='data',
  serialized_pb=_b('\n\x16\x65xercise_sensors.proto\x12\x04\x64\x61ta\x1a\x10structures.proto\"q\n\x10PbExerciseSensor\x12\x16\n\x03mac\x18\x01 \x02(\x0b\x32\t.PbBleMac\x12\x1e\n\tdevice_id\x18\x02 \x01(\x0b\x32\x0b.PbDeviceId\x12%\n\x0b\x64\x65vice_name\x18\x03 \x01(\x0b\x32\x10.PbBleDeviceName\"<\n\x11PbExerciseSensors\x12\'\n\x07sensors\x18\x01 \x03(\x0b\x32\x16.data.PbExerciseSensor')
  ,
  dependencies=[structures_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PBEXERCISESENSOR = _descriptor.Descriptor(
  name='PbExerciseSensor',
  full_name='data.PbExerciseSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mac', full_name='data.PbExerciseSensor.mac', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='data.PbExerciseSensor.device_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device_name', full_name='data.PbExerciseSensor.device_name', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=163,
)


_PBEXERCISESENSORS = _descriptor.Descriptor(
  name='PbExerciseSensors',
  full_name='data.PbExerciseSensors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensors', full_name='data.PbExerciseSensors.sensors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=225,
)

_PBEXERCISESENSOR.fields_by_name['mac'].message_type = structures_pb2._PBBLEMAC
_PBEXERCISESENSOR.fields_by_name['device_id'].message_type = structures_pb2._PBDEVICEID
_PBEXERCISESENSOR.fields_by_name['device_name'].message_type = structures_pb2._PBBLEDEVICENAME
_PBEXERCISESENSORS.fields_by_name['sensors'].message_type = _PBEXERCISESENSOR
DESCRIPTOR.message_types_by_name['PbExerciseSensor'] = _PBEXERCISESENSOR
DESCRIPTOR.message_types_by_name['PbExerciseSensors'] = _PBEXERCISESENSORS

PbExerciseSensor = _reflection.GeneratedProtocolMessageType('PbExerciseSensor', (_message.Message,), dict(
  DESCRIPTOR = _PBEXERCISESENSOR,
  __module__ = 'exercise_sensors_pb2'
  # @@protoc_insertion_point(class_scope:data.PbExerciseSensor)
  ))
_sym_db.RegisterMessage(PbExerciseSensor)

PbExerciseSensors = _reflection.GeneratedProtocolMessageType('PbExerciseSensors', (_message.Message,), dict(
  DESCRIPTOR = _PBEXERCISESENSORS,
  __module__ = 'exercise_sensors_pb2'
  # @@protoc_insertion_point(class_scope:data.PbExerciseSensors)
  ))
_sym_db.RegisterMessage(PbExerciseSensors)


# @@protoc_insertion_point(module_scope)
