# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exercise_phases_reps.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import exercise_stats_pb2
import types_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='exercise_phases_reps.proto',
  package='data',
  serialized_pb=_b('\n\x1a\x65xercise_phases_reps.proto\x12\x04\x64\x61ta\x1a\x14\x65xercise_stats.proto\x1a\x0btypes.proto\">\n\x1aPbPhaseHeartRateStatistics\x12\x0f\n\x07\x61verage\x18\x01 \x01(\r\x12\x0f\n\x07maximum\x18\x02 \x01(\r\"0\n\x1dPbPhaseStrideLengthStatistics\x12\x0f\n\x07\x61verage\x18\x01 \x01(\r\"\xd7\x04\n\x11PbPhaseRepetition\x12\r\n\x05index\x18\x01 \x02(\r\x12\x1f\n\nsplit_time\x18\x02 \x02(\x0b\x32\x0b.PbDuration\x12\x1d\n\x08\x64uration\x18\x03 \x02(\x0b\x32\x0b.PbDuration\x12\x16\n\x0ephase_finished\x18\x04 \x01(\x08\x12\x16\n\x0esplit_distance\x18\x05 \x01(\x02\x12\x10\n\x08\x64istance\x18\x06 \x01(\x02\x12#\n\x0ein_target_zone\x18\x07 \x01(\x0b\x32\x0b.PbDuration\x12\x34\n\nheart_rate\x18\x08 \x01(\x0b\x32 .data.PbPhaseHeartRateStatistics\x12&\n\x05speed\x18\t \x01(\x0b\x32\x17.data.PbSpeedStatistics\x12*\n\x07\x63\x61\x64\x65nce\x18\n \x01(\x0b\x32\x19.data.PbCadenceStatistics\x12&\n\x05power\x18\x0b \x01(\x0b\x32\x17.data.PbPowerStatistics\x12\x37\n\x12left_right_balance\x18\x0c \x01(\x0b\x32\x1b.data.PbLRBalanceStatistics\x12:\n\rstride_length\x18\r \x01(\x0b\x32#.data.PbPhaseStrideLengthStatistics\x12\x14\n\x0cstroke_count\x18\x0e \x01(\r\x12\x15\n\raverage_swolf\x18\x0f \x01(\x02\x12\x17\n\x0fstrokes_per_min\x18\x10 \x01(\r\x12\x0e\n\x06\x61scent\x18\x11 \x01(\x02\x12\x0f\n\x07\x64\x65scent\x18\x12 \x01(\x02\"<\n\x12PbPhaseRepetitions\x12&\n\x05phase\x18\x01 \x03(\x0b\x32\x17.data.PbPhaseRepetition')
  ,
  dependencies=[exercise_stats_pb2.DESCRIPTOR,types_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PBPHASEHEARTRATESTATISTICS = _descriptor.Descriptor(
  name='PbPhaseHeartRateStatistics',
  full_name='data.PbPhaseHeartRateStatistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='average', full_name='data.PbPhaseHeartRateStatistics.average', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maximum', full_name='data.PbPhaseHeartRateStatistics.maximum', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=133,
)


_PBPHASESTRIDELENGTHSTATISTICS = _descriptor.Descriptor(
  name='PbPhaseStrideLengthStatistics',
  full_name='data.PbPhaseStrideLengthStatistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='average', full_name='data.PbPhaseStrideLengthStatistics.average', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=183,
)


_PBPHASEREPETITION = _descriptor.Descriptor(
  name='PbPhaseRepetition',
  full_name='data.PbPhaseRepetition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='data.PbPhaseRepetition.index', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='split_time', full_name='data.PbPhaseRepetition.split_time', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration', full_name='data.PbPhaseRepetition.duration', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phase_finished', full_name='data.PbPhaseRepetition.phase_finished', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='split_distance', full_name='data.PbPhaseRepetition.split_distance', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='distance', full_name='data.PbPhaseRepetition.distance', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='in_target_zone', full_name='data.PbPhaseRepetition.in_target_zone', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='heart_rate', full_name='data.PbPhaseRepetition.heart_rate', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='data.PbPhaseRepetition.speed', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cadence', full_name='data.PbPhaseRepetition.cadence', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='power', full_name='data.PbPhaseRepetition.power', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='left_right_balance', full_name='data.PbPhaseRepetition.left_right_balance', index=11,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stride_length', full_name='data.PbPhaseRepetition.stride_length', index=12,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stroke_count', full_name='data.PbPhaseRepetition.stroke_count', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='average_swolf', full_name='data.PbPhaseRepetition.average_swolf', index=14,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strokes_per_min', full_name='data.PbPhaseRepetition.strokes_per_min', index=15,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ascent', full_name='data.PbPhaseRepetition.ascent', index=16,
      number=17, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='descent', full_name='data.PbPhaseRepetition.descent', index=17,
      number=18, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=785,
)


_PBPHASEREPETITIONS = _descriptor.Descriptor(
  name='PbPhaseRepetitions',
  full_name='data.PbPhaseRepetitions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phase', full_name='data.PbPhaseRepetitions.phase', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=787,
  serialized_end=847,
)

_PBPHASEREPETITION.fields_by_name['split_time'].message_type = types_pb2._PBDURATION
_PBPHASEREPETITION.fields_by_name['duration'].message_type = types_pb2._PBDURATION
_PBPHASEREPETITION.fields_by_name['in_target_zone'].message_type = types_pb2._PBDURATION
_PBPHASEREPETITION.fields_by_name['heart_rate'].message_type = _PBPHASEHEARTRATESTATISTICS
_PBPHASEREPETITION.fields_by_name['speed'].message_type = exercise_stats_pb2._PBSPEEDSTATISTICS
_PBPHASEREPETITION.fields_by_name['cadence'].message_type = exercise_stats_pb2._PBCADENCESTATISTICS
_PBPHASEREPETITION.fields_by_name['power'].message_type = exercise_stats_pb2._PBPOWERSTATISTICS
_PBPHASEREPETITION.fields_by_name['left_right_balance'].message_type = exercise_stats_pb2._PBLRBALANCESTATISTICS
_PBPHASEREPETITION.fields_by_name['stride_length'].message_type = _PBPHASESTRIDELENGTHSTATISTICS
_PBPHASEREPETITIONS.fields_by_name['phase'].message_type = _PBPHASEREPETITION
DESCRIPTOR.message_types_by_name['PbPhaseHeartRateStatistics'] = _PBPHASEHEARTRATESTATISTICS
DESCRIPTOR.message_types_by_name['PbPhaseStrideLengthStatistics'] = _PBPHASESTRIDELENGTHSTATISTICS
DESCRIPTOR.message_types_by_name['PbPhaseRepetition'] = _PBPHASEREPETITION
DESCRIPTOR.message_types_by_name['PbPhaseRepetitions'] = _PBPHASEREPETITIONS

PbPhaseHeartRateStatistics = _reflection.GeneratedProtocolMessageType('PbPhaseHeartRateStatistics', (_message.Message,), dict(
  DESCRIPTOR = _PBPHASEHEARTRATESTATISTICS,
  __module__ = 'exercise_phases_reps_pb2'
  # @@protoc_insertion_point(class_scope:data.PbPhaseHeartRateStatistics)
  ))
_sym_db.RegisterMessage(PbPhaseHeartRateStatistics)

PbPhaseStrideLengthStatistics = _reflection.GeneratedProtocolMessageType('PbPhaseStrideLengthStatistics', (_message.Message,), dict(
  DESCRIPTOR = _PBPHASESTRIDELENGTHSTATISTICS,
  __module__ = 'exercise_phases_reps_pb2'
  # @@protoc_insertion_point(class_scope:data.PbPhaseStrideLengthStatistics)
  ))
_sym_db.RegisterMessage(PbPhaseStrideLengthStatistics)

PbPhaseRepetition = _reflection.GeneratedProtocolMessageType('PbPhaseRepetition', (_message.Message,), dict(
  DESCRIPTOR = _PBPHASEREPETITION,
  __module__ = 'exercise_phases_reps_pb2'
  # @@protoc_insertion_point(class_scope:data.PbPhaseRepetition)
  ))
_sym_db.RegisterMessage(PbPhaseRepetition)

PbPhaseRepetitions = _reflection.GeneratedProtocolMessageType('PbPhaseRepetitions', (_message.Message,), dict(
  DESCRIPTOR = _PBPHASEREPETITIONS,
  __module__ = 'exercise_phases_reps_pb2'
  # @@protoc_insertion_point(class_scope:data.PbPhaseRepetitions)
  ))
_sym_db.RegisterMessage(PbPhaseRepetitions)


# @@protoc_insertion_point(module_scope)
