# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data/exercise_route2.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2 as types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='data/exercise_route2.proto',
  package='data',
  syntax='proto2',
  serialized_pb=_b('\n\x1a\x64\x61ta/exercise_route2.proto\x12\x04\x64\x61ta\x1a\x0btypes.proto\":\n\x13PbLocationSyncPoint\x12\x10\n\x08latitude\x18\x01 \x02(\x01\x12\x11\n\tlongitude\x18\x02 \x02(\x01\"\x83\x02\n\x18PbExerciseRouteSyncPoint\x12\r\n\x05index\x18\x01 \x02(\r\x12+\n\x08location\x18\x02 \x01(\x0b\x32\x19.data.PbLocationSyncPoint\x12(\n\rgps_date_time\x18\x03 \x01(\x0b\x32\x11.PbSystemDateTime\x12\x13\n\x08\x61ltitude\x18\x04 \x01(\x11:\x01\x30\x12#\n\x16\x63oordinate_granularity\x18\x05 \x01(\r:\x03\x31\x30\x30\x12#\n\x15timestamp_granularity\x18\x06 \x01(\r:\x04\x31\x30\x30\x30\x12\"\n\x14\x61ltitude_granularity\x18\x07 \x01(\r:\x04\x31\x30\x30\x30\"\xb1\x01\n\x17PbExerciseRouteSamples2\x12\x32\n\nsync_point\x18\x01 \x03(\x0b\x32\x1e.data.PbExerciseRouteSyncPoint\x12\x18\n\x10satellite_amount\x18\x02 \x03(\r\x12\x10\n\x08latitude\x18\x03 \x03(\x12\x12\x11\n\tlongitude\x18\x04 \x03(\x12\x12\x11\n\ttimestamp\x18\x05 \x03(\x11\x12\x10\n\x08\x61ltitude\x18\x06 \x03(\x12')
  ,
  dependencies=[types__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PBLOCATIONSYNCPOINT = _descriptor.Descriptor(
  name='PbLocationSyncPoint',
  full_name='data.PbLocationSyncPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='data.PbLocationSyncPoint.latitude', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='data.PbLocationSyncPoint.longitude', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=107,
)


_PBEXERCISEROUTESYNCPOINT = _descriptor.Descriptor(
  name='PbExerciseRouteSyncPoint',
  full_name='data.PbExerciseRouteSyncPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='data.PbExerciseRouteSyncPoint.index', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='data.PbExerciseRouteSyncPoint.location', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gps_date_time', full_name='data.PbExerciseRouteSyncPoint.gps_date_time', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='data.PbExerciseRouteSyncPoint.altitude', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coordinate_granularity', full_name='data.PbExerciseRouteSyncPoint.coordinate_granularity', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=100,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp_granularity', full_name='data.PbExerciseRouteSyncPoint.timestamp_granularity', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='altitude_granularity', full_name='data.PbExerciseRouteSyncPoint.altitude_granularity', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=369,
)


_PBEXERCISEROUTESAMPLES2 = _descriptor.Descriptor(
  name='PbExerciseRouteSamples2',
  full_name='data.PbExerciseRouteSamples2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sync_point', full_name='data.PbExerciseRouteSamples2.sync_point', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='satellite_amount', full_name='data.PbExerciseRouteSamples2.satellite_amount', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='data.PbExerciseRouteSamples2.latitude', index=2,
      number=3, type=18, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='data.PbExerciseRouteSamples2.longitude', index=3,
      number=4, type=18, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='data.PbExerciseRouteSamples2.timestamp', index=4,
      number=5, type=17, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='data.PbExerciseRouteSamples2.altitude', index=5,
      number=6, type=18, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=372,
  serialized_end=549,
)

_PBEXERCISEROUTESYNCPOINT.fields_by_name['location'].message_type = _PBLOCATIONSYNCPOINT
_PBEXERCISEROUTESYNCPOINT.fields_by_name['gps_date_time'].message_type = types__pb2._PBSYSTEMDATETIME
_PBEXERCISEROUTESAMPLES2.fields_by_name['sync_point'].message_type = _PBEXERCISEROUTESYNCPOINT
DESCRIPTOR.message_types_by_name['PbLocationSyncPoint'] = _PBLOCATIONSYNCPOINT
DESCRIPTOR.message_types_by_name['PbExerciseRouteSyncPoint'] = _PBEXERCISEROUTESYNCPOINT
DESCRIPTOR.message_types_by_name['PbExerciseRouteSamples2'] = _PBEXERCISEROUTESAMPLES2

PbLocationSyncPoint = _reflection.GeneratedProtocolMessageType('PbLocationSyncPoint', (_message.Message,), dict(
  DESCRIPTOR = _PBLOCATIONSYNCPOINT,
  __module__ = 'data.exercise_route2_pb2'
  # @@protoc_insertion_point(class_scope:data.PbLocationSyncPoint)
  ))
_sym_db.RegisterMessage(PbLocationSyncPoint)

PbExerciseRouteSyncPoint = _reflection.GeneratedProtocolMessageType('PbExerciseRouteSyncPoint', (_message.Message,), dict(
  DESCRIPTOR = _PBEXERCISEROUTESYNCPOINT,
  __module__ = 'data.exercise_route2_pb2'
  # @@protoc_insertion_point(class_scope:data.PbExerciseRouteSyncPoint)
  ))
_sym_db.RegisterMessage(PbExerciseRouteSyncPoint)

PbExerciseRouteSamples2 = _reflection.GeneratedProtocolMessageType('PbExerciseRouteSamples2', (_message.Message,), dict(
  DESCRIPTOR = _PBEXERCISEROUTESAMPLES2,
  __module__ = 'data.exercise_route2_pb2'
  # @@protoc_insertion_point(class_scope:data.PbExerciseRouteSamples2)
  ))
_sym_db.RegisterMessage(PbExerciseRouteSamples2)


# @@protoc_insertion_point(module_scope)
