# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jumptest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='jumptest.proto',
  package='data',
  serialized_pb=_b('\n\x0ejumptest.proto\x12\x04\x64\x61ta\x1a\x0btypes.proto\"M\n\x06PbJump\x12 \n\x0b\x66light_time\x18\x01 \x02(\x0b\x32\x0b.PbDuration\x12!\n\x0c\x63ontact_time\x18\x02 \x01(\x0b\x32\x0b.PbDuration\"\x92\x02\n\nPbJumpTest\x12\x32\n\ttest_type\x18\x01 \x02(\x0e\x32\x1f.data.PbJumpTest.PbJumpTestType\x12$\n\nstart_time\x18\x02 \x02(\x0b\x32\x10.PbLocalDateTime\x12\x1a\n\x04jump\x18\x03 \x03(\x0b\x32\x0c.data.PbJump\x12\'\n\x12\x63ont_jump_duration\x18\x04 \x01(\x0b\x32\x0b.PbDuration\"e\n\x0ePbJumpTestType\x12\x18\n\x14JUMP_TEST_TYPE_SQUAT\x10\x00\x12\x1a\n\x16JUMP_TEST_TYPE_COUNTER\x10\x01\x12\x1d\n\x19JUMP_TEST_TYPE_CONTINUOUS\x10\x02')
  ,
  dependencies=[types_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PBJUMPTEST_PBJUMPTESTTYPE = _descriptor.EnumDescriptor(
  name='PbJumpTestType',
  full_name='data.PbJumpTest.PbJumpTestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='JUMP_TEST_TYPE_SQUAT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JUMP_TEST_TYPE_COUNTER', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JUMP_TEST_TYPE_CONTINUOUS', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=290,
  serialized_end=391,
)
_sym_db.RegisterEnumDescriptor(_PBJUMPTEST_PBJUMPTESTTYPE)


_PBJUMP = _descriptor.Descriptor(
  name='PbJump',
  full_name='data.PbJump',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='flight_time', full_name='data.PbJump.flight_time', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contact_time', full_name='data.PbJump.contact_time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=114,
)


_PBJUMPTEST = _descriptor.Descriptor(
  name='PbJumpTest',
  full_name='data.PbJumpTest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='test_type', full_name='data.PbJumpTest.test_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='data.PbJumpTest.start_time', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='jump', full_name='data.PbJumpTest.jump', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cont_jump_duration', full_name='data.PbJumpTest.cont_jump_duration', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PBJUMPTEST_PBJUMPTESTTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=391,
)

_PBJUMP.fields_by_name['flight_time'].message_type = types_pb2._PBDURATION
_PBJUMP.fields_by_name['contact_time'].message_type = types_pb2._PBDURATION
_PBJUMPTEST.fields_by_name['test_type'].enum_type = _PBJUMPTEST_PBJUMPTESTTYPE
_PBJUMPTEST.fields_by_name['start_time'].message_type = types_pb2._PBLOCALDATETIME
_PBJUMPTEST.fields_by_name['jump'].message_type = _PBJUMP
_PBJUMPTEST.fields_by_name['cont_jump_duration'].message_type = types_pb2._PBDURATION
_PBJUMPTEST_PBJUMPTESTTYPE.containing_type = _PBJUMPTEST
DESCRIPTOR.message_types_by_name['PbJump'] = _PBJUMP
DESCRIPTOR.message_types_by_name['PbJumpTest'] = _PBJUMPTEST

PbJump = _reflection.GeneratedProtocolMessageType('PbJump', (_message.Message,), dict(
  DESCRIPTOR = _PBJUMP,
  __module__ = 'jumptest_pb2'
  # @@protoc_insertion_point(class_scope:data.PbJump)
  ))
_sym_db.RegisterMessage(PbJump)

PbJumpTest = _reflection.GeneratedProtocolMessageType('PbJumpTest', (_message.Message,), dict(
  DESCRIPTOR = _PBJUMPTEST,
  __module__ = 'jumptest_pb2'
  # @@protoc_insertion_point(class_scope:data.PbJumpTest)
  ))
_sym_db.RegisterMessage(PbJumpTest)


# @@protoc_insertion_point(module_scope)
