# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map_information.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='map_information.proto',
  package='data',
  serialized_pb=_b('\n\x15map_information.proto\x12\x04\x64\x61ta\x1a\x0btypes.proto\"4\n\rPbMapLocation\x12\x10\n\x08latitude\x18\x01 \x02(\x01\x12\x11\n\tlongitude\x18\x02 \x02(\x01\"\x80\x01\n\x10PbMapInformation\x12)\n\x0c\x63\x65ntre_point\x18\x01 \x02(\x0b\x32\x13.data.PbMapLocation\x12)\n\x0e\x64\x61ta_timestamp\x18\x02 \x01(\x0b\x32\x11.PbSystemDateTime\x12\x16\n\x07updated\x18\x03 \x01(\x08:\x05\x66\x61lse')
  ,
  dependencies=[types_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PBMAPLOCATION = _descriptor.Descriptor(
  name='PbMapLocation',
  full_name='data.PbMapLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='data.PbMapLocation.latitude', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='data.PbMapLocation.longitude', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=96,
)


_PBMAPINFORMATION = _descriptor.Descriptor(
  name='PbMapInformation',
  full_name='data.PbMapInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='centre_point', full_name='data.PbMapInformation.centre_point', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data_timestamp', full_name='data.PbMapInformation.data_timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='updated', full_name='data.PbMapInformation.updated', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=227,
)

_PBMAPINFORMATION.fields_by_name['centre_point'].message_type = _PBMAPLOCATION
_PBMAPINFORMATION.fields_by_name['data_timestamp'].message_type = types_pb2._PBSYSTEMDATETIME
DESCRIPTOR.message_types_by_name['PbMapLocation'] = _PBMAPLOCATION
DESCRIPTOR.message_types_by_name['PbMapInformation'] = _PBMAPINFORMATION

PbMapLocation = _reflection.GeneratedProtocolMessageType('PbMapLocation', (_message.Message,), dict(
  DESCRIPTOR = _PBMAPLOCATION,
  __module__ = 'map_information_pb2'
  # @@protoc_insertion_point(class_scope:data.PbMapLocation)
  ))
_sym_db.RegisterMessage(PbMapLocation)

PbMapInformation = _reflection.GeneratedProtocolMessageType('PbMapInformation', (_message.Message,), dict(
  DESCRIPTOR = _PBMAPINFORMATION,
  __module__ = 'map_information_pb2'
  # @@protoc_insertion_point(class_scope:data.PbMapInformation)
  ))
_sym_db.RegisterMessage(PbMapInformation)


# @@protoc_insertion_point(module_scope)
