# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orthostatictestresult.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='orthostatictestresult.proto',
  package='data',
  serialized_pb=_b('\n\x1borthostatictestresult.proto\x12\x04\x64\x61ta\x1a\x0btypes.proto\"\xa6\x02\n\x17PbOrthostaticTestResult\x12$\n\nstart_time\x18\x01 \x02(\x0b\x32\x10.PbLocalDateTime\x12$\n\nreset_time\x18\x02 \x02(\x0b\x32\x10.PbLocalDateTime\x12\x15\n\rrr_avg_supine\x18\x03 \x02(\r\x12\"\n\x1arr_long_term_avg_of_supine\x18\x04 \x02(\r\x12\x1c\n\x14rr_min_after_standup\x18\x05 \x02(\r\x12-\n%rr_long_term_avg_of_min_after_standup\x18\x06 \x02(\r\x12\x14\n\x0crr_avg_stand\x18\x07 \x02(\r\x12!\n\x19rr_long_term_avg_of_stand\x18\x08 \x02(\r')
  ,
  dependencies=[types_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PBORTHOSTATICTESTRESULT = _descriptor.Descriptor(
  name='PbOrthostaticTestResult',
  full_name='data.PbOrthostaticTestResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_time', full_name='data.PbOrthostaticTestResult.start_time', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reset_time', full_name='data.PbOrthostaticTestResult.reset_time', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rr_avg_supine', full_name='data.PbOrthostaticTestResult.rr_avg_supine', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rr_long_term_avg_of_supine', full_name='data.PbOrthostaticTestResult.rr_long_term_avg_of_supine', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rr_min_after_standup', full_name='data.PbOrthostaticTestResult.rr_min_after_standup', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rr_long_term_avg_of_min_after_standup', full_name='data.PbOrthostaticTestResult.rr_long_term_avg_of_min_after_standup', index=5,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rr_avg_stand', full_name='data.PbOrthostaticTestResult.rr_avg_stand', index=6,
      number=7, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rr_long_term_avg_of_stand', full_name='data.PbOrthostaticTestResult.rr_long_term_avg_of_stand', index=7,
      number=8, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=345,
)

_PBORTHOSTATICTESTRESULT.fields_by_name['start_time'].message_type = types_pb2._PBLOCALDATETIME
_PBORTHOSTATICTESTRESULT.fields_by_name['reset_time'].message_type = types_pb2._PBLOCALDATETIME
DESCRIPTOR.message_types_by_name['PbOrthostaticTestResult'] = _PBORTHOSTATICTESTRESULT

PbOrthostaticTestResult = _reflection.GeneratedProtocolMessageType('PbOrthostaticTestResult', (_message.Message,), dict(
  DESCRIPTOR = _PBORTHOSTATICTESTRESULT,
  __module__ = 'orthostatictestresult_pb2'
  # @@protoc_insertion_point(class_scope:data.PbOrthostaticTestResult)
  ))
_sym_db.RegisterMessage(PbOrthostaticTestResult)


# @@protoc_insertion_point(module_scope)
