# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pftp_request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pftp_request.proto',
  package='protocol',
  serialized_pb=_b('\n\x12pftp_request.proto\x12\x08protocol\x1a\x0btypes.proto\"\x87\x01\n\x0fPbPFtpOperation\x12\x32\n\x07\x63ommand\x18\x01 \x02(\x0e\x32!.protocol.PbPFtpOperation.Command\x12\x0c\n\x04path\x18\x02 \x02(\t\"2\n\x07\x43ommand\x12\x07\n\x03GET\x10\x00\x12\x07\n\x03PUT\x10\x01\x12\t\n\x05MERGE\x10\x02\x12\n\n\x06REMOVE\x10\x03\"Z\n\x19PbPFtpSetSystemTimeParams\x12\x15\n\x04\x64\x61te\x18\x01 \x02(\x0b\x32\x07.PbDate\x12\x15\n\x04time\x18\x02 \x02(\x0b\x32\x07.PbTime\x12\x0f\n\x07trusted\x18\x03 \x02(\x08\"[\n\x18PbPFtpSetLocalTimeParams\x12\x15\n\x04\x64\x61te\x18\x01 \x02(\x0b\x32\x07.PbDate\x12\x15\n\x04time\x18\x02 \x02(\x0b\x32\x07.PbTime\x12\x11\n\ttz_offset\x18\x03 \x01(\x05\"D\n\"PbPFtpGenerateChallengeTokenParams\x12\x0f\n\x07user_id\x18\x01 \x02(\r\x12\r\n\x05nonse\x18\x02 \x02(\x0c\"(\n\x16PbPFtpSetAdbModeParams\x12\x0e\n\x06\x65nable\x18\x01 \x02(\x08\"6\n\x1cPbPFtpCleanupDiskSpaceParams\x12\x16\n\x0erequired_bytes\x18\x01 \x02(\x04*\x9d\x02\n\x0bPbPFtpQuery\x12\x13\n\x0fIDENTIFY_DEVICE\x10\x00\x12\x13\n\x0fSET_SYSTEM_TIME\x10\x01\x12\x13\n\x0fGET_SYSTEM_TIME\x10\x02\x12\x12\n\x0eSET_LOCAL_TIME\x10\x03\x12\x12\n\x0eGET_LOCAL_TIME\x10\x04\x12\x12\n\x0eGET_DISK_SPACE\x10\x05\x12\x1c\n\x18GENERATE_CHALLENGE_TOKEN\x10\x06\x12\x15\n\x11SET_INTERNAL_TEST\x10\x07\x12\x16\n\x12GET_BATTERY_STATUS\x10\x08\x12\x10\n\x0cSET_ADB_MODE\x10\t\x12\x16\n\x12\x43LEANUP_DISK_SPACE\x10\n\x12\x1c\n\x18GET_INACTIVITY_PRE_ALERT\x10\x0b')
  ,
  dependencies=[types_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_PBPFTPQUERY = _descriptor.EnumDescriptor(
  name='PbPFtpQuery',
  full_name='protocol.PbPFtpQuery',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IDENTIFY_DEVICE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_SYSTEM_TIME', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_SYSTEM_TIME', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_LOCAL_TIME', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_LOCAL_TIME', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_DISK_SPACE', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GENERATE_CHALLENGE_TOKEN', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_INTERNAL_TEST', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_BATTERY_STATUS', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_ADB_MODE', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLEANUP_DISK_SPACE', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_INACTIVITY_PRE_ALERT', index=11, number=11,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=537,
  serialized_end=822,
)
_sym_db.RegisterEnumDescriptor(_PBPFTPQUERY)

PbPFtpQuery = enum_type_wrapper.EnumTypeWrapper(_PBPFTPQUERY)
IDENTIFY_DEVICE = 0
SET_SYSTEM_TIME = 1
GET_SYSTEM_TIME = 2
SET_LOCAL_TIME = 3
GET_LOCAL_TIME = 4
GET_DISK_SPACE = 5
GENERATE_CHALLENGE_TOKEN = 6
SET_INTERNAL_TEST = 7
GET_BATTERY_STATUS = 8
SET_ADB_MODE = 9
CLEANUP_DISK_SPACE = 10
GET_INACTIVITY_PRE_ALERT = 11


_PBPFTPOPERATION_COMMAND = _descriptor.EnumDescriptor(
  name='Command',
  full_name='protocol.PbPFtpOperation.Command',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GET', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PUT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MERGE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REMOVE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=131,
  serialized_end=181,
)
_sym_db.RegisterEnumDescriptor(_PBPFTPOPERATION_COMMAND)


_PBPFTPOPERATION = _descriptor.Descriptor(
  name='PbPFtpOperation',
  full_name='protocol.PbPFtpOperation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='protocol.PbPFtpOperation.command', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path', full_name='protocol.PbPFtpOperation.path', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PBPFTPOPERATION_COMMAND,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=181,
)


_PBPFTPSETSYSTEMTIMEPARAMS = _descriptor.Descriptor(
  name='PbPFtpSetSystemTimeParams',
  full_name='protocol.PbPFtpSetSystemTimeParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='protocol.PbPFtpSetSystemTimeParams.date', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='protocol.PbPFtpSetSystemTimeParams.time', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trusted', full_name='protocol.PbPFtpSetSystemTimeParams.trusted', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=273,
)


_PBPFTPSETLOCALTIMEPARAMS = _descriptor.Descriptor(
  name='PbPFtpSetLocalTimeParams',
  full_name='protocol.PbPFtpSetLocalTimeParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='protocol.PbPFtpSetLocalTimeParams.date', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='protocol.PbPFtpSetLocalTimeParams.time', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tz_offset', full_name='protocol.PbPFtpSetLocalTimeParams.tz_offset', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=366,
)


_PBPFTPGENERATECHALLENGETOKENPARAMS = _descriptor.Descriptor(
  name='PbPFtpGenerateChallengeTokenParams',
  full_name='protocol.PbPFtpGenerateChallengeTokenParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='protocol.PbPFtpGenerateChallengeTokenParams.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nonse', full_name='protocol.PbPFtpGenerateChallengeTokenParams.nonse', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=436,
)


_PBPFTPSETADBMODEPARAMS = _descriptor.Descriptor(
  name='PbPFtpSetAdbModeParams',
  full_name='protocol.PbPFtpSetAdbModeParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enable', full_name='protocol.PbPFtpSetAdbModeParams.enable', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=438,
  serialized_end=478,
)


_PBPFTPCLEANUPDISKSPACEPARAMS = _descriptor.Descriptor(
  name='PbPFtpCleanupDiskSpaceParams',
  full_name='protocol.PbPFtpCleanupDiskSpaceParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='required_bytes', full_name='protocol.PbPFtpCleanupDiskSpaceParams.required_bytes', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=480,
  serialized_end=534,
)

_PBPFTPOPERATION.fields_by_name['command'].enum_type = _PBPFTPOPERATION_COMMAND
_PBPFTPOPERATION_COMMAND.containing_type = _PBPFTPOPERATION
_PBPFTPSETSYSTEMTIMEPARAMS.fields_by_name['date'].message_type = types_pb2._PBDATE
_PBPFTPSETSYSTEMTIMEPARAMS.fields_by_name['time'].message_type = types_pb2._PBTIME
_PBPFTPSETLOCALTIMEPARAMS.fields_by_name['date'].message_type = types_pb2._PBDATE
_PBPFTPSETLOCALTIMEPARAMS.fields_by_name['time'].message_type = types_pb2._PBTIME
DESCRIPTOR.message_types_by_name['PbPFtpOperation'] = _PBPFTPOPERATION
DESCRIPTOR.message_types_by_name['PbPFtpSetSystemTimeParams'] = _PBPFTPSETSYSTEMTIMEPARAMS
DESCRIPTOR.message_types_by_name['PbPFtpSetLocalTimeParams'] = _PBPFTPSETLOCALTIMEPARAMS
DESCRIPTOR.message_types_by_name['PbPFtpGenerateChallengeTokenParams'] = _PBPFTPGENERATECHALLENGETOKENPARAMS
DESCRIPTOR.message_types_by_name['PbPFtpSetAdbModeParams'] = _PBPFTPSETADBMODEPARAMS
DESCRIPTOR.message_types_by_name['PbPFtpCleanupDiskSpaceParams'] = _PBPFTPCLEANUPDISKSPACEPARAMS
DESCRIPTOR.enum_types_by_name['PbPFtpQuery'] = _PBPFTPQUERY

PbPFtpOperation = _reflection.GeneratedProtocolMessageType('PbPFtpOperation', (_message.Message,), dict(
  DESCRIPTOR = _PBPFTPOPERATION,
  __module__ = 'pftp_request_pb2'
  # @@protoc_insertion_point(class_scope:protocol.PbPFtpOperation)
  ))
_sym_db.RegisterMessage(PbPFtpOperation)

PbPFtpSetSystemTimeParams = _reflection.GeneratedProtocolMessageType('PbPFtpSetSystemTimeParams', (_message.Message,), dict(
  DESCRIPTOR = _PBPFTPSETSYSTEMTIMEPARAMS,
  __module__ = 'pftp_request_pb2'
  # @@protoc_insertion_point(class_scope:protocol.PbPFtpSetSystemTimeParams)
  ))
_sym_db.RegisterMessage(PbPFtpSetSystemTimeParams)

PbPFtpSetLocalTimeParams = _reflection.GeneratedProtocolMessageType('PbPFtpSetLocalTimeParams', (_message.Message,), dict(
  DESCRIPTOR = _PBPFTPSETLOCALTIMEPARAMS,
  __module__ = 'pftp_request_pb2'
  # @@protoc_insertion_point(class_scope:protocol.PbPFtpSetLocalTimeParams)
  ))
_sym_db.RegisterMessage(PbPFtpSetLocalTimeParams)

PbPFtpGenerateChallengeTokenParams = _reflection.GeneratedProtocolMessageType('PbPFtpGenerateChallengeTokenParams', (_message.Message,), dict(
  DESCRIPTOR = _PBPFTPGENERATECHALLENGETOKENPARAMS,
  __module__ = 'pftp_request_pb2'
  # @@protoc_insertion_point(class_scope:protocol.PbPFtpGenerateChallengeTokenParams)
  ))
_sym_db.RegisterMessage(PbPFtpGenerateChallengeTokenParams)

PbPFtpSetAdbModeParams = _reflection.GeneratedProtocolMessageType('PbPFtpSetAdbModeParams', (_message.Message,), dict(
  DESCRIPTOR = _PBPFTPSETADBMODEPARAMS,
  __module__ = 'pftp_request_pb2'
  # @@protoc_insertion_point(class_scope:protocol.PbPFtpSetAdbModeParams)
  ))
_sym_db.RegisterMessage(PbPFtpSetAdbModeParams)

PbPFtpCleanupDiskSpaceParams = _reflection.GeneratedProtocolMessageType('PbPFtpCleanupDiskSpaceParams', (_message.Message,), dict(
  DESCRIPTOR = _PBPFTPCLEANUPDISKSPACEPARAMS,
  __module__ = 'pftp_request_pb2'
  # @@protoc_insertion_point(class_scope:protocol.PbPFtpCleanupDiskSpaceParams)
  ))
_sym_db.RegisterMessage(PbPFtpCleanupDiskSpaceParams)


# @@protoc_insertion_point(module_scope)
