# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: poi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import structures_pb2
import types_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='poi.proto',
  package='data',
  serialized_pb=_b('\n\tpoi.proto\x12\x04\x64\x61ta\x1a\x10structures.proto\x1a\x0btypes.proto\"\xc1\x01\n\x11PbPointOfInterest\x12\x1d\n\x08location\x18\x01 \x02(\x0b\x32\x0b.PbLocation\x12\x10\n\x08point_id\x18\x02 \x01(\x04\x12\x1e\n\x04name\x18\x03 \x01(\x0b\x32\x10.PbMultiLineText\x12\r\n\x05\x61larm\x18\x04 \x01(\x08\x12\"\n\x07\x63reated\x18\x64 \x01(\x0b\x32\x11.PbSystemDateTime\x12(\n\rlast_modified\x18\x65 \x01(\x0b\x32\x11.PbSystemDateTime\"<\n\x12PbPointOfInterests\x12&\n\x05point\x18\x01 \x03(\x0b\x32\x17.data.PbPointOfInterest')
  ,
  dependencies=[structures_pb2.DESCRIPTOR,types_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PBPOINTOFINTEREST = _descriptor.Descriptor(
  name='PbPointOfInterest',
  full_name='data.PbPointOfInterest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='data.PbPointOfInterest.location', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point_id', full_name='data.PbPointOfInterest.point_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='data.PbPointOfInterest.name', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='alarm', full_name='data.PbPointOfInterest.alarm', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='created', full_name='data.PbPointOfInterest.created', index=4,
      number=100, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_modified', full_name='data.PbPointOfInterest.last_modified', index=5,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=244,
)


_PBPOINTOFINTERESTS = _descriptor.Descriptor(
  name='PbPointOfInterests',
  full_name='data.PbPointOfInterests',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='point', full_name='data.PbPointOfInterests.point', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=306,
)

_PBPOINTOFINTEREST.fields_by_name['location'].message_type = types_pb2._PBLOCATION
_PBPOINTOFINTEREST.fields_by_name['name'].message_type = structures_pb2._PBMULTILINETEXT
_PBPOINTOFINTEREST.fields_by_name['created'].message_type = types_pb2._PBSYSTEMDATETIME
_PBPOINTOFINTEREST.fields_by_name['last_modified'].message_type = types_pb2._PBSYSTEMDATETIME
_PBPOINTOFINTERESTS.fields_by_name['point'].message_type = _PBPOINTOFINTEREST
DESCRIPTOR.message_types_by_name['PbPointOfInterest'] = _PBPOINTOFINTEREST
DESCRIPTOR.message_types_by_name['PbPointOfInterests'] = _PBPOINTOFINTERESTS

PbPointOfInterest = _reflection.GeneratedProtocolMessageType('PbPointOfInterest', (_message.Message,), dict(
  DESCRIPTOR = _PBPOINTOFINTEREST,
  __module__ = 'poi_pb2'
  # @@protoc_insertion_point(class_scope:data.PbPointOfInterest)
  ))
_sym_db.RegisterMessage(PbPointOfInterest)

PbPointOfInterests = _reflection.GeneratedProtocolMessageType('PbPointOfInterests', (_message.Message,), dict(
  DESCRIPTOR = _PBPOINTOFINTERESTS,
  __module__ = 'poi_pb2'
  # @@protoc_insertion_point(class_scope:data.PbPointOfInterests)
  ))
_sym_db.RegisterMessage(PbPointOfInterests)


# @@protoc_insertion_point(module_scope)
