# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sportprofile_avalon_settings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sportprofile_avalon_settings.proto',
  package='data',
  serialized_pb=_b('\n\"sportprofile_avalon_settings.proto\x12\x04\x64\x61ta\"\x9a\x02\n\x1cPbAvalonSportProfileSettings\x12\x44\n\x0bheart_touch\x18\x01 \x01(\x0e\x32/.data.PbAvalonSportProfileSettings.PbHeartTouch\x12\x11\n\tvibration\x18\x03 \x01(\x08\x12\x12\n\nauto_start\x18\x04 \x01(\x08\"\x8c\x01\n\x0cPbHeartTouch\x12\x13\n\x0fHEART_TOUCH_OFF\x10\x01\x12\"\n\x1eHEART_TOUCH_ACTIVATE_BACKLIGHT\x10\x02\x12!\n\x1dHEART_TOUCH_SHOW_PREVIOUS_LAP\x10\x03\x12 \n\x1cHEART_TOUCH_SHOW_TIME_OF_DAY\x10\x04')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PBAVALONSPORTPROFILESETTINGS_PBHEARTTOUCH = _descriptor.EnumDescriptor(
  name='PbHeartTouch',
  full_name='data.PbAvalonSportProfileSettings.PbHeartTouch',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HEART_TOUCH_OFF', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEART_TOUCH_ACTIVATE_BACKLIGHT', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEART_TOUCH_SHOW_PREVIOUS_LAP', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEART_TOUCH_SHOW_TIME_OF_DAY', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=187,
  serialized_end=327,
)
_sym_db.RegisterEnumDescriptor(_PBAVALONSPORTPROFILESETTINGS_PBHEARTTOUCH)


_PBAVALONSPORTPROFILESETTINGS = _descriptor.Descriptor(
  name='PbAvalonSportProfileSettings',
  full_name='data.PbAvalonSportProfileSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='heart_touch', full_name='data.PbAvalonSportProfileSettings.heart_touch', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vibration', full_name='data.PbAvalonSportProfileSettings.vibration', index=1,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='auto_start', full_name='data.PbAvalonSportProfileSettings.auto_start', index=2,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PBAVALONSPORTPROFILESETTINGS_PBHEARTTOUCH,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=327,
)

_PBAVALONSPORTPROFILESETTINGS.fields_by_name['heart_touch'].enum_type = _PBAVALONSPORTPROFILESETTINGS_PBHEARTTOUCH
_PBAVALONSPORTPROFILESETTINGS_PBHEARTTOUCH.containing_type = _PBAVALONSPORTPROFILESETTINGS
DESCRIPTOR.message_types_by_name['PbAvalonSportProfileSettings'] = _PBAVALONSPORTPROFILESETTINGS

PbAvalonSportProfileSettings = _reflection.GeneratedProtocolMessageType('PbAvalonSportProfileSettings', (_message.Message,), dict(
  DESCRIPTOR = _PBAVALONSPORTPROFILESETTINGS,
  __module__ = 'sportprofile_avalon_settings_pb2'
  # @@protoc_insertion_point(class_scope:data.PbAvalonSportProfileSettings)
  ))
_sym_db.RegisterMessage(PbAvalonSportProfileSettings)


# @@protoc_insertion_point(module_scope)
