# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sportprofile_maserati_settings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sportprofile_maserati_settings.proto',
  package='data',
  serialized_pb=_b('\n$sportprofile_maserati_settings.proto\x12\x04\x64\x61ta\"\xfc\x03\n\x1ePbMaseratiSportProfileSettings\x12\x46\n\x0bheart_touch\x18\x01 \x01(\x0e\x32\x31.data.PbMaseratiSportProfileSettings.PbHeartTouch\x12Q\n\x11tap_button_action\x18\x02 \x01(\x0e\x32\x36.data.PbMaseratiSportProfileSettings.PbTapButtonAction\x12\x11\n\tvibration\x18\x03 \x01(\x08\x12\x12\n\nauto_start\x18\x04 \x01(\x08\"\x8c\x01\n\x0cPbHeartTouch\x12\x13\n\x0fHEART_TOUCH_OFF\x10\x01\x12\"\n\x1eHEART_TOUCH_ACTIVATE_BACKLIGHT\x10\x02\x12!\n\x1dHEART_TOUCH_SHOW_PREVIOUS_LAP\x10\x03\x12 \n\x1cHEART_TOUCH_SHOW_TIME_OF_DAY\x10\x04\"\x88\x01\n\x11PbTapButtonAction\x12\x12\n\x0eTAP_BUTTON_OFF\x10\x01\x12\x17\n\x13TAP_BUTTON_TAKE_LAP\x10\x02\x12#\n\x1fTAP_BUTTON_CHANGE_TRAINING_VIEW\x10\x03\x12!\n\x1dTAP_BUTTON_ACTIVATE_BACKLIGHT\x10\x04')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PBMASERATISPORTPROFILESETTINGS_PBHEARTTOUCH = _descriptor.EnumDescriptor(
  name='PbHeartTouch',
  full_name='data.PbMaseratiSportProfileSettings.PbHeartTouch',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HEART_TOUCH_OFF', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEART_TOUCH_ACTIVATE_BACKLIGHT', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEART_TOUCH_SHOW_PREVIOUS_LAP', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEART_TOUCH_SHOW_TIME_OF_DAY', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=276,
  serialized_end=416,
)
_sym_db.RegisterEnumDescriptor(_PBMASERATISPORTPROFILESETTINGS_PBHEARTTOUCH)

_PBMASERATISPORTPROFILESETTINGS_PBTAPBUTTONACTION = _descriptor.EnumDescriptor(
  name='PbTapButtonAction',
  full_name='data.PbMaseratiSportProfileSettings.PbTapButtonAction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TAP_BUTTON_OFF', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TAP_BUTTON_TAKE_LAP', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TAP_BUTTON_CHANGE_TRAINING_VIEW', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TAP_BUTTON_ACTIVATE_BACKLIGHT', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=419,
  serialized_end=555,
)
_sym_db.RegisterEnumDescriptor(_PBMASERATISPORTPROFILESETTINGS_PBTAPBUTTONACTION)


_PBMASERATISPORTPROFILESETTINGS = _descriptor.Descriptor(
  name='PbMaseratiSportProfileSettings',
  full_name='data.PbMaseratiSportProfileSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='heart_touch', full_name='data.PbMaseratiSportProfileSettings.heart_touch', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tap_button_action', full_name='data.PbMaseratiSportProfileSettings.tap_button_action', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vibration', full_name='data.PbMaseratiSportProfileSettings.vibration', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='auto_start', full_name='data.PbMaseratiSportProfileSettings.auto_start', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PBMASERATISPORTPROFILESETTINGS_PBHEARTTOUCH,
    _PBMASERATISPORTPROFILESETTINGS_PBTAPBUTTONACTION,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=555,
)

_PBMASERATISPORTPROFILESETTINGS.fields_by_name['heart_touch'].enum_type = _PBMASERATISPORTPROFILESETTINGS_PBHEARTTOUCH
_PBMASERATISPORTPROFILESETTINGS.fields_by_name['tap_button_action'].enum_type = _PBMASERATISPORTPROFILESETTINGS_PBTAPBUTTONACTION
_PBMASERATISPORTPROFILESETTINGS_PBHEARTTOUCH.containing_type = _PBMASERATISPORTPROFILESETTINGS
_PBMASERATISPORTPROFILESETTINGS_PBTAPBUTTONACTION.containing_type = _PBMASERATISPORTPROFILESETTINGS
DESCRIPTOR.message_types_by_name['PbMaseratiSportProfileSettings'] = _PBMASERATISPORTPROFILESETTINGS

PbMaseratiSportProfileSettings = _reflection.GeneratedProtocolMessageType('PbMaseratiSportProfileSettings', (_message.Message,), dict(
  DESCRIPTOR = _PBMASERATISPORTPROFILESETTINGS,
  __module__ = 'sportprofile_maserati_settings_pb2'
  # @@protoc_insertion_point(class_scope:data.PbMaseratiSportProfileSettings)
  ))
_sym_db.RegisterMessage(PbMaseratiSportProfileSettings)


# @@protoc_insertion_point(module_scope)
